"""Pydantic models for the ParsedContent standard format.

This is the single contract between the parse layer and the display layer.
Every parse template must produce a ParsedContent instance.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Chapter(BaseModel):
    """Single podcast chapter entry generated by LLM."""

    start_min: int = 0      # approximate minute offset in the episode
    title: str = ""
    description: str = ""


class ParsedArticle(BaseModel):
    """Structured article data produced by LLM parsing."""

    title: str = ""
    summary: str = ""                       # 5-sentence summary
    key_points: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    author: str = ""
    clean_content: str = ""                 # Markdown body, cleaned and structured
    reading_time: int = 0                   # estimated minutes
    word_count: int = 0
    chapters: list[Chapter] = Field(default_factory=list)  # podcast chapters (audio only)


class AIMeta(BaseModel):
    """Metadata about the LLM call used for parsing."""

    model: str = ""
    tokens_used: int = 0
    template_version: str = "1.0"


class ParsedContent(BaseModel):
    """Standard output format produced by every parse template.

    Serialised to: data/parsed/{YYYYMMDD}/{uuid}.json
    """

    id: UUID = Field(default_factory=uuid4)
    raw_file: str = ""                      # path to the source RawCapture file
    parsed_at: datetime = Field(default_factory=lambda: datetime.utcnow())
    template_used: str = ""
    article: ParsedArticle = Field(default_factory=ParsedArticle)
    ai_meta: AIMeta = Field(default_factory=AIMeta)
    status: str = "parsed"

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json")
